//
//  RatingControl.swift
//  FoodTracker
//
//  Created by JE10890 on 26/08/2019.
//  Copyright © 2019 JE10890. All rights reserved.
//

import UIKit

@objcMembers @IBDesignable
class RatingControl: UIStackView {
    
    
    //MARK: Properties
    private var ratingButtons = [UIButton]()
    
    var rating = 0
    
    @IBInspectable var starSize: CGSize = CGSize(width: 44.0, height: 44.0)
    @IBInspectable var starCount: Int = 5
    
    //MARK: Initialization
    
    override init(frame: CGRect) {
        super.init(frame: frame)
        setupButtons()
    }
    
    required init(coder: NSCoder) {
        super.init(coder: coder)
        setupButtons()
    }
    
    //MARK: Button Action
    func ratingButtonTapped(button: UIButton){
        print("button pressed 🤓")
    }
    
    //MARK: Private Methods
    
    private func setupButtons(){
        for _ in 0..<starCount {
            //Create the button
            let button = UIButton();
            button.backgroundColor = .red
            
            //Add constraints
            button.translatesAutoresizingMaskIntoConstraints = false //Disable autogenerated constraints
            button.heightAnchor.constraint(equalToConstant: starSize.height).isActive = true
            button.widthAnchor.constraint(equalToConstant: starSize.width).isActive = true
            
            // Setup the button action
            button.addTarget(self, action: #selector(RatingControl.ratingButtonTapped(button:)), for: .touchUpInside)
            
            //Add the button to the stack
            addArrangedSubview(button)
            
            // Add the new button to the rating button array
            ratingButtons.append(button)
        }
    }
}
